import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '../components/Navbar'; // Import the Navbar component
import React from 'react';
import { AuthProvider } from '@/stores/user';
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <section>
            {children}
          </section>
        </AuthProvider>
      </body>
    </html>
  );
}
