import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '../components/Navbar'; // Import the Navbar component
import React from 'react';
import { AuthProvider } from '@/stores/user';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <>
            <Navbar /> {/* Use the Navbar component here */}
          </>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
