# Generated by Django 4.2.13 on 2024-06-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('musician', 'Musician'), ('productor', 'Productor'), ('both', 'Musician and Productor')], default='both', max_length=20),
        ),
        migrations.AlterField(
            model_name='pastwork',
            name='image',
            field=models.ImageField(upload_to='static/past_work_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('musician', 'Musician'), ('productor', 'Productor'), ('both', 'Musician and Productor')], default='musician', max_length=10),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(upload_to='static/skills_images/'),
        ),
    ]
