# Generated by Django 4.2.13 on 2024-06-10 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_role_alter_pastwork_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
