# Generated by Django 4.2.13 on 2024-06-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('musician', 'Musician'), ('productor', 'Productor')], default='musician', max_length=10),
        ),
    ]
