# Generated by Django 4.2.13 on 2024-06-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_city_profile_links_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('musician', 'Musician'), ('producer', 'Producer')], default='musician', max_length=10),
        ),
    ]
